# Generated by Django 4.2.20 on 2025-06-09 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('up_to_date', 'Up to date'), ('update_available', 'Update available'), ('not_installed', 'Not installed')], default='up_to_date', max_length=20)),
                ('icon', models.CharField(default='cube', max_length=50)),
                ('icon_color', models.CharField(default='indigo', max_length=50)),
                ('install_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-install_date'],
            },
        ),
    ]
